import { formatLocal } from './util.mjs';

const pct = (a, b) => (b ? `${((100 * a) / b).toFixed(1)}%` : 'n/a');
const table = (head, rows) => [
  `| ${head.join(' | ')} |`,
  `| ${head.map(() => '---').join(' | ')} |`,
  ...rows.map(r => `| ${r.join(' | ')} |`),
].join('\n');

function tally(items, keyFn) {
  const m = new Map();
  for (const x of items) { const k = keyFn(x); m.set(k, (m.get(k) ?? 0) + 1); }
  return [...m].sort(([a], [b]) => String(a).localeCompare(String(b)));
}

/** Redacted aggregate report. Contains no prompt text, paths, raw session ids or account ids. */
export function renderReport({ runs, policy, feedback, labels, problems, timeZone }) {
  const out = [];
  out.push('# Routing evidence report');
  out.push('');
  out.push('Generated by `node Analyzer/cli.mjs report`. Aggregates and redacted evidence IDs (`ev-…`, sha256 of the private session key) only; transcripts, prompts, paths and private extracts stay in `Analyzer/private/` (Git-ignored). Model names are recorded exactly as observed; anything not observed is written as `unknown`.');
  out.push('');
  if (!runs.length) { out.push('No analyzer runs found.'); return out.join('\n') + '\n'; }

  out.push('## Runs');
  out.push(table(['run', 'window', 'now (UTC)', 'now (local)', 'window start (local)', 'seed', 'rate'],
    runs.map(r => [r.id, r.manifest.window, r.manifest.now, formatLocal(Date.parse(r.manifest.now), r.manifest.timeZone ?? timeZone), formatLocal(Date.parse(r.manifest.windowStart), r.manifest.timeZone ?? timeZone), `\`${r.manifest.seed}\``, r.manifest.rate])));
  out.push('');
  out.push('');
  out.push('## At a glance');
  for (const r of runs) {
    const reviewed = (r.review?.labels ?? []).filter(l => l.reviewed);
    const s = reviewed.filter(l => l.outcome === 'success' && l.basis !== 'test').length;
    const c = reviewed.filter(l => l.outcome === 'success' && l.basis === 'test').length;
    const f = reviewed.filter(l => l.outcome === 'failure').length;
    out.push(`- ${r.manifest.window}: ${r.sample.denominator} eligible sessions, ${r.sample.randomSampled} randomly sampled and ${reviewed.length} manually reviewed (${pct(reviewed.length, r.sample.denominator)}); user/QA-confirmed success ${s}, failure ${f}, check-level test passes ${c} (not task success), unknown ${reviewed.length - s - f - c}.`);
  }
  const r24 = runs.find(r => r.manifest.window === '24h');
  if (r24 && runs.some(r => r.manifest.window === '48h')) {
    const known24 = (r24.review?.labels ?? []).filter(l => l.reviewed && l.outcome !== 'unknown' && l.basis !== 'test').length;
    const validated = policy?.rules.filter(x => x.status === 'validated').length ?? 0;
    out.push(`- The 24h review produced ${known24} known outcomes (expansion rule: fewer than 10, or no task/CLI/model/effort group with 5), so the window was expanded once to 48h, the stated maximum.${validated ? '' : ' Evidence is still insufficient: every proposed rule stays `candidate` and routing keeps its existing cold-start behaviour.'}`);
  }
  if (policy) out.push(`- Proposed policy: ${policy.rules.length} candidate/validated rules (${policy.rules.filter(x => x.status === 'validated').length} validated); \`docs/routing-policy.json\` untouched.`);
  out.push('');
  out.push('Reproduce, in order: `analyze --window 24h --now <now UTC> --seed <seed>`, `review label` every sampled packet, `expand-check --run <24h run>`, and only if it says so `analyze --window 48h` with the same `--now`/`--seed` (0–24h labels carry over) plus `review label` for the new picks; then `compile --now <now UTC>` and `report`. All commands are `node Analyzer/cli.mjs …`.');
  out.push('');

  for (const r of runs) {
    const sessions = r.inventory.sessions;
    const eligible = sessions.filter(s => !s.exclusion);
    const labelByKey = new Map((r.review?.labels ?? []).map(l => [l.key, l]));
    out.push(`## Run ${r.id}`);
    out.push('');
    out.push('### Sources scanned');
    out.push(table(['cli', 'roots', 'files modified in window', 'accounts'], r.inventory.sources.map(s => [s.cli, s.roots, s.files, s.accounts ?? '-'])));
    out.push('');
    const j = r.inventory.jev;
    out.push(`JEV decision sources: ${j.statusFiles} status files (${j.statusDecisions} decisions, ${j.statusDecisionsInWindow} in window; ${j.manualStatus} manual-model markers), audit log ${j.auditRows} rows (${j.auditRowsInWindow} in window), runtime decisions ${j.runtimeDecisions}, runtime feedback ${j.runtimeFeedback}. ${j.note}`);
    out.push('');
    if (r.inventory.missing.length) out.push(`Missing or empty: ${r.inventory.missing.join('; ')}.`);
    out.push('');
    out.push('### Denominator');
    const d = r.inventory.dedupe;
    out.push(`${d.parsedFiles} files parsed → ${d.distinctSessions} distinct sessions after same-session dedupe (${d.mergedFiles} files merged into an existing session, ${d.droppedDuplicateEvents} duplicate events dropped).`);
    out.push('');
    out.push(table(['exclusion', 'sessions'], [...tally(sessions.filter(s => s.exclusion), s => s.exclusion), ['**eligible**', `**${eligible.length}**`]]));
    out.push('');
    out.push('Eligible = activity inside the window (events after `now` ignored), at least one human-authored user message (harness/system injections excluded) and at least one assistant turn or command.');
    out.push('');
    out.push('### Sample');
    out.push(table(['stratum (band / cli / routing / kind)', 'eligible', 'random sample', 'reviewed', 'success', 'failure', 'unknown'],
      r.sample.strata.map(st => {
        const picks = r.sample.picks.filter(p => p.stratum === st.stratum).map(p => labelByKey.get(p.key)).filter(Boolean);
        const rev = picks.filter(l => l.reviewed);
        return [st.stratum.split('|').join(' / '), st.eligible, st.sampled, rev.length, rev.filter(l => l.outcome === 'success').length, rev.filter(l => l.outcome === 'failure').length, rev.filter(l => l.outcome === 'unknown').length];
      })));
    out.push('');
    const reviewedRandom = r.sample.picks.filter(p => p.reason === 'random' && labelByKey.get(p.key)?.reviewed).length;
    out.push(`Random sample ${r.sample.randomSampled}/${r.sample.denominator} eligible sessions = **${pct(r.sample.randomSampled, r.sample.denominator)}** (ceil 20% per stratum); manually reviewed ${reviewedRandom}/${r.sample.denominator} = **${pct(reviewedRandom, r.sample.denominator)}**. Purposive additions (known cases, not counted in coverage): ${r.sample.purposiveSampled}.`);
    out.push('');
    out.push('### Routing split (eligible)');
    out.push(table(['cli', 'routing', 'sessions'], tally(eligible, s => `${s.cli}|${s.routing}`).map(([k, n]) => [...k.split('|'), n])));
    out.push('');
    out.push('Routing: `jev-routed` = JEV decision/notice linked to the session; `jev-manual` = session ran under JEV with a manually chosen model; `not-routed` = Codex session whose provider/model show no JEV; `not-observed` = no JEV evidence found (Claude/AGY sessions cannot prove absence).');
    out.push('');
    out.push('### Models observed (eligible sessions)');
    const modelRows = new Map();
    for (const s of eligible) {
      for (const m of s.models) {
        if (m.model === 'unknown' && s.observedModels.length) continue; // metadata rows below name it
        const k = `${s.cli}|${m.model}|${m.effort ?? 'unknown'}|${m.source}`;
        const row = modelRows.get(k) ?? { sessions: 0, turns: 0 };
        row.sessions++; row.turns += m.turns; modelRows.set(k, row);
      }
      for (const m of s.observedModels) {
        const k = `${s.cli}|${m.model}|unknown|${m.source}`;
        const row = modelRows.get(k) ?? { sessions: 0, turns: 0 };
        row.sessions++; row.turns += m.count; modelRows.set(k, row);
      }
      if (!s.models.length && !s.observedModels.length) {
        const k = `${s.cli}|unknown|unknown|none`;
        const row = modelRows.get(k) ?? { sessions: 0, turns: 0 };
        row.sessions++; modelRows.set(k, row);
      }
    }
    out.push(table(['cli', 'exact model string', 'effort', 'provenance', 'sessions', 'turns/records'],
      [...modelRows].sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => [...k.split('|').map(x => `\`${x}\``), v.sessions, v.turns])));
    out.push('');
    out.push('Claude effort is the transcript `effort` field (client/router setting). Codex effort under `jev-router` comes from the in-transcript JEV notice; AGY reports JEV aliases (e.g. `gemini-pro-agent`) plus whatever model strings appear in generation metadata — the alias does not identify a release.');
    out.push('');
    const known = r.known ?? [];
    for (const k of known) {
      out.push(`### Known case: ${k.id}`);
      if (!k.found) { out.push(`Not re-verified in this run: ${k.reason ?? 'destructive command not found'}.`); out.push(''); continue; }
      const kl = labelByKey.get(r.inventory.sessions.find(s => s.evidenceId === k.evidenceId)?.key);
      out.push(`Evidence ${k.evidenceId}${k.reportedBy ? ` (reported in ${k.reportedBy})` : ''}, eligible in window: ${k.eligible}.`);
      out.push(`- Routing notices: ${k.routingNotices.map(n => `${n.ref} → \`${n.model}\` (${n.reason}, confidence ${n.confidence})`).join('; ')}.`);
      out.push(`- Model strings in generation metadata: ${k.observedModels.map(m => `\`${m}\``).join(', ') || 'none'}; model enums: ${k.modelEnums.map(m => `\`${m}\``).join(', ') || 'none'}. Exact Gemini release: unknown.`);
      out.push(`- Destructive commands: ${k.destructive.map(x => `${x.ref}→${x.resultRef ?? '?'} ${x.kinds.join(' + ')} exit=${x.exitCode ?? 'unknown'}`).join('; ')}; ${k.deletionLinesShown} \`Removing …\` lines visible plus ${k.deletionLinesTruncated} truncated output lines.`);
      const a = k.authorization;
      out.push(`- Authorizing user messages before the command: ${a.userMessagesBeforeCommand.join(', ')}. Asked to restore: ${a.userAskedToRestore.join(', ') || 'none'}. Granted general autonomy: ${a.userGrantedGeneralAutonomy.join(', ') || 'none'}. Asked to discard/clean: ${a.userAskedToDiscardOrClean.join(', ') || 'none'}.`);
      out.push(`- Transcript-only instructions mentioning reset/restore (model-written directives, subagent prompts): ${a.transcriptOnlyMentions.join(', ') || 'none'}. These are not user authorization.`);
      out.push(`- Conclusion: ${a.conclusion}.`);
      if (kl?.reviewed) out.push(`- Review label: **${kl.outcome}** (basis ${kl.basis}; cites ${kl.citations.join(', ')}); attributed to \`${kl.attribution.cli}\` / \`${kl.attribution.model}\` / effort \`${kl.attribution.effort ?? 'unknown'}\`.`);
      out.push('- This is one failure. It does not rank models and is not applied retrospectively to today\'s candidate list.');
      out.push('');
    }
  }

  out.push('## Reviewed outcomes (all runs, one label per session)');
  const kindOf = l => (l.outcome === 'success' && l.basis === 'test' ? 'check-level pass' : l.outcome === 'success' ? 'confirmed success' : l.outcome);
  out.push(table(['cli', 'outcome', 'basis', 'sessions'], tally(labels, l => `${l.attribution?.cli}|${kindOf(l)}|${l.basis}`).map(([k, n]) => [...k.split('|'), n])));
  out.push('');
  out.push('`confirmed success` and `failure` cite a human follow-up (user or person-run QA) and are attributed to the model/effort of the turns that follow-up reacts to; a mixed or unobserved source abstains. A `check-level pass` cites a test run that passed after the last edit: it shows the check passed, not that the request was met, and never counts as policy success. An assistant saying "done" is never counted. Everything else stays `unknown`.');
  out.push('');
  const examples = labels.filter(l => l.outcome !== 'unknown').slice(0, 12);
  if (examples.length) {
    out.push(table(['evidence', 'cli', 'model', 'effort', 'taskType', 'outcome', 'basis'],
      examples.map(l => [l.evidenceId, l.attribution.cli, `\`${l.attribution.model}\``, l.attribution.effort ?? 'unknown', l.taskType, kindOf(l), l.basis])));
    out.push('');
  }
  if (problems.length) out.push(`Rejected by validation: ${problems.length} (${problems.map(p => p.evidenceId ?? p.feedback).join(', ')}).\n`);

  out.push('## Feedback intake');
  out.push(`Records: ${feedback.length} (verified ${feedback.filter(f => f.verified).length}, awaiting adjudication ${feedback.filter(f => !f.verified).length}). By source: ${tally(feedback, f => f.source).map(([k, n]) => `${k} ${n}`).join(', ') || 'none'}. Authorized-by: ${tally(feedback, f => f.authorizedBy).map(([k, n]) => `${k} ${n}`).join(', ') || 'none'}.`);
  out.push('');

  out.push('## Proposed policy (not applied)');
  if (!policy) out.push('No proposed policy compiled yet.');
  else {
    out.push(`\`Analyzer/private/proposed-policy.json\` version \`${policy.version}\`, generated ${policy.generatedAt}: ${policy.rules.length} rules (${policy.rules.filter(r => r.status === 'validated').length} validated), ${policy.abstained.length} abstentions. \`docs/routing-policy.json\` is unchanged.`);
    out.push('');
    if (policy.rules.length) {
      out.push(table(['rule', 'status', 'n', 'success', 'failure', 'unknown', 'check-only passes (in unknown)', 'evidenceAt', 'evidence'],
        policy.rules.map(r => [`\`${r.id}\``, r.status, r.sampleSize, r.successes, r.failures, r.unknown, r.checkOnlyPasses ?? 0, r.evidenceAt ?? 'n/a', r.evidenceIds.slice(0, 6).join(' ') + (r.evidenceIds.length > 6 ? ' …' : '')])));
      out.push('');
    }
  }
  out.push('## Limits');
  out.push('- Outcomes are adjudicated only from explicit user/QA statements or executed test output visible in the transcript; sessions without them are `unknown`, which is most sessions.');
  out.push('- Latency, cost and token efficiency were not measured and no comparative model ranking is claimed.');
  out.push('- Antigravity protobuf fields are decoded without a published schema; unmatched fields yield `unknown`.');
  out.push('- JEV status files for Codex/AGY are keyed by process id and linked only by exact prompt match; Claude status files are keyed by session id.');
  return out.join('\n') + '\n';
}
